matrix:
  include:
    - os: linux
      dist: xenial
    - os: osx
      osx_image: xcode10
sudo: required
language: 
    - go
go: 
    - 1.10.8
    - 1.12.4
script:
    - go build ./cmd/gptn
    - $GOPATH/bin/goveralls -service=travis-ci
    - cp gptn bdd/node
    - cd bdd/node
    - pwd
    - chmod +x gptn
    - python -V
    - python init.py
    - nohup ./gptn &
    - sleep 15
    - netstat -ap | grep gptn
    - cd ../dct
    - ./deposit_test.sh 4
    - python -m robot.run ../testcase/createTrans
after_success:
    - killall gptn
after_failure:
    - killall gptn
    
before_install:
    - go get -u github.com/mattn/goveralls
    - go get -u github.com/palletone/adaptor
    - go get -u github.com/palletone/btc-adaptor
    - go get -u github.com/palletone/eth-adaptor
    - go get -u github.com/palletone/digital-identity/...
    - source ./gomockgen.sh
 
install: 
    - sudo -H pip install --upgrade pip
    - sudo -H pip install robotframework==2.8.5
    - sudo -H pip install requests
    - sudo -H pip install robotframework-requests
    - sudo -H pip install demjson 
    - sudo -H pip install pexpect 
    #- sudo -H apt-get install expect
    #- sudo -H apt-get install jq tcl tk

addons:
    apt:
        update: true
